
spring:
  web:
    locale: ko
    resources:
      chain:
        compressed: true
        cache: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri:
            client-authentication-method: POST
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kauth.kakao.com/v2/user/me
          user-name-attribute: id
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090
  servlet:
    session:
      timeout: 7200
      cookie:
        name:
    encoding:
      charset: UTF-8
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false
    path: /error

# 사용자설정
properties:
  common:
    security:
      ignores: /css/**, /fonts/**, /img/**, /js/**
      permit-alls: /api/auth/**, /api/oauth2/**
      redirect-url: /
      iframe-option: disable #disable, same-origin, deny
      cors:
        pattern: /** #/auth/**
        allowed-origins: "*"
        allowed-methods: "*" #PUT,DELETE,GET,POST ...
        allowed-headers: "*" #Context-Type, ...
      same-site: Lax #None, Lax, Strict
    token:
      prefix:
      token-name:
      access-token-expire-time: 1800000 #30분
      #access-token-expire-time: 60000 # for test: 1분
      refresh-token-expire-time: 604800000 #7일
      secret: